# Generated by Django 6.0.3 on 2026-04-27 08:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_structured_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('vendor', models.CharField(max_length=120)),
                ('base_url', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('default_model', models.CharField(max_length=120)),
                ('timeout', models.PositiveIntegerField(default=30)),
                ('retry_count', models.PositiveIntegerField(default=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
            options={
                'db_table': 'ai_model_source',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('temperature', models.FloatField(default=0.2)),
                ('top_p', models.FloatField(default=0.9)),
                ('max_tokens', models.PositiveIntegerField(default=2048)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
            options={
                'db_table': 'organization_model_config',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=160)),
                ('display_name', models.CharField(max_length=160)),
                ('module', models.CharField(default='LLM解释', max_length=120)),
                ('use_case', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
            options={
                'db_table': 'provider_model',
                'ordering': ['model_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-operation_time']},
        ),
        migrations.RenameIndex(
            model_name='structureddetectionresult',
            new_name='core_struct_created_9d52b0_idx',
            old_name='core_structu_created_324f6f_idx',
        ),
        migrations.RemoveField(
            model_name='log',
            name='id',
        ),
        migrations.RemoveField(
            model_name='log',
            name='related_id',
        ),
        migrations.RemoveField(
            model_name='log',
            name='related_model',
        ),
        migrations.AddField(
            model_name='log',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='is_anomaly',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='log',
            name='operation_detail',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='result',
            field=models.CharField(default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='log',
            name='target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='target_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='user_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detectiontask',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='operation_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='log',
            name='operation_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload', 'Upload'), ('ai_detect', 'AI Detection'), ('audit_submit', 'Audit Submit'), ('audit_op', 'Audit Operation'), ('comment', 'Comment'), ('like', 'Like'), ('report', 'Report'), ('entity_create', 'Entity Create'), ('entity_delete', 'Entity Delete'), ('entity_update', 'Entity Update'), ('model_config_change', 'Model Config Change'), ('report_handle', 'Report Handle'), ('detection', 'Detection'), ('review_request', 'Review Request'), ('manual_review', 'Manual Review'), ('resource_container', 'Resource Container'), ('file_bind', 'File Bind'), ('review_text', 'Review Text'), ('material_validation', 'Material Validation')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', 'operation_type', 'operation_time'], name='core_log_user_id_2f792a_idx'),
        ),
        migrations.AddField(
            model_name='aimodelsource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmodelconfig',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_configs', to='core.organization'),
        ),
        migrations.AddField(
            model_name='organizationmodelconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_model_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providermodel',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_models', to='core.aimodelsource'),
        ),
        migrations.AddField(
            model_name='organizationmodelconfig',
            name='provider_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_configs', to='core.providermodel'),
        ),
        migrations.AlterUniqueTogether(
            name='providermodel',
            unique_together={('source', 'model_id')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationmodelconfig',
            unique_together={('organization', 'provider_model')},
        ),
    ]
