# Generated by Django 6.0.3 on 2026-05-10 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aimodelsource_organizationmodelconfig_providermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiontask',
            name='task_type',
            field=models.CharField(choices=[('image', '图像检测'), ('paper_text', '论文文本检测'), ('review_text', 'Review文本检测'), ('multi_material', '综合检测')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='manualreview',
            name='text_resources',
            field=models.ManyToManyField(blank=True, related_name='manual_reviews', to='core.reviewtextresource'),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='text_resources',
            field=models.ManyToManyField(blank=True, related_name='review_requests', to='core.reviewtextresource'),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='status',
            field=models.CharField(choices=[('in_progress', '正在检测中'), ('completed', '检测已完成'), ('failed', '检测失败')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='detectiontask',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('partially_completed', '部分完成'), ('failed', '失败')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='operation_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload', 'Upload'), ('ai_detect', 'AI Detection'), ('paper_detect', 'Paper Text Detection'), ('review_detect', 'Review Text Detection'), ('audit_submit', 'Audit Submit'), ('audit_op', 'Audit Operation'), ('comment', 'Comment'), ('like', 'Like'), ('report', 'Report'), ('entity_create', 'Entity Create'), ('entity_delete', 'Entity Delete'), ('entity_update', 'Entity Update'), ('model_config_change', 'Model Config Change'), ('report_handle', 'Report Handle'), ('detection', 'Detection'), ('review_request', 'Review Request'), ('manual_review', 'Manual Review'), ('resource_container', 'Resource Container'), ('file_bind', 'File Bind'), ('review_text', 'Review Text'), ('material_validation', 'Material Validation')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='manualreview',
            name='img_reviews',
            field=models.ManyToManyField(blank=True, related_name='manual_reviews', to='core.imagereview'),
        ),
        migrations.AlterField(
            model_name='manualreview',
            name='imgs',
            field=models.ManyToManyField(blank=True, related_name='manual_reviews', to='core.imageupload'),
        ),
        migrations.AlterField(
            model_name='reviewrequest',
            name='detection_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='core.detectionresult'),
        ),
        migrations.AlterField(
            model_name='reviewrequest',
            name='imgs',
            field=models.ManyToManyField(blank=True, related_name='review_requests', to='core.imageupload'),
        ),
        migrations.CreateModel(
            name='TextDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', '正在检测中'), ('completed', '检测已完成'), ('failed', '检测失败')], default='in_progress', max_length=20)),
                ('detection_time', models.DateTimeField(blank=True, null=True)),
                ('is_fake', models.BooleanField(null=True)),
                ('confidence_score', models.FloatField(null=True)),
                ('ai_generated_paragraphs', models.JSONField(blank=True, help_text='AI生成的文本段落详情及概率', null=True)),
                ('factual_fake_reason', models.TextField(blank=True, help_text='事实性鉴伪子结论与原因', null=True)),
                ('template_tendency_score', models.FloatField(blank=True, help_text='模板化倾向评分', null=True)),
                ('template_analysis_reason', models.TextField(blank=True, help_text='模板化倾向分析原因', null=True)),
                ('is_under_review', models.BooleanField(default=False)),
                ('detection_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_detection_results', to='core.detectiontask')),
                ('text_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_results', to='core.reviewtextresource')),
            ],
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='text_detection_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='core.textdetectionresult'),
        ),
        migrations.CreateModel(
            name='TextReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_reviews', models.JSONField(blank=True, null=True)),
                ('template_review_score', models.FloatField(blank=True, null=True)),
                ('template_review_comment', models.TextField(blank=True, null=True)),
                ('overall_comment', models.TextField(blank=True, null=True)),
                ('result', models.BooleanField(help_text='最终判定真假结果(True为造假)', null=True)),
                ('review_time', models.DateTimeField(db_index=True, default=django.utils.timezone.localtime)),
                ('manual_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_reviews', to='core.manualreview')),
                ('text_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_reviews', to='core.reviewtextresource')),
            ],
        ),
        migrations.CreateModel(
            name='LLMAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=80, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('output_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_analysis_runs', to=settings.AUTH_USER_MODEL)),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_runs', to='core.organizationmodelconfig')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_analysis_runs', to='core.detectiontask')),
            ],
            options={
                'db_table': 'llm_analysis_run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='llm_analysi_task_id_99601f_idx'), models.Index(fields=['status', 'created_at'], name='llm_analysi_status_5c25da_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='textdetectionresult',
            index=models.Index(fields=['detection_task', 'status'], name='core_textde_detecti_ac202b_idx'),
        ),
    ]
