# Generated by Django 6.0.3 on 2026-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_detectiontask_task_type_manualreview_text_resources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanagement',
            name='tag',
            field=models.CharField(
                choices=[
                    ('computer_science', 'Computer Science'),
                    ('artificial_intelligence', 'Artificial Intelligence'),
                    ('mathematics', 'Mathematics'),
                    ('physics', 'Physics'),
                    ('chemistry', 'Chemistry'),
                    ('biology', 'Biology'),
                    ('medicine', 'Medicine'),
                    ('engineering', 'Engineering'),
                    ('graphics', 'Graphics'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=30,
            ),
        ),
    ]
