# Generated by Django 6.0.3 on 2026-05-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_filemanagement_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectiontask',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('analyzing', '大模型分析中'), ('completed', '已完成'), ('partially_completed', '部分完成'), ('failed', '失败')], default='pending', max_length=20),
        ),
    ]
