# Generated by Copilot on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_alter_detectiontask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtextresource',
            name='isReview',
            field=models.BooleanField(default=False),
        ),
    ]
