# Generated by Copilot on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_reviewtextresource_isreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='detection_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='review_requests', to='core.detectiontask'),
        ),
    ]
