# Generated by Django 6.0.3 on 2026-05-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reviewrequest_detection_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='operation_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload', 'Upload'), ('ai_detect', 'AI Detection'), ('paper_detect', 'Paper Text Detection'), ('review_detect', 'Review Text Detection'), ('audit_submit', 'Audit Submit'), ('audit_op', 'Audit Operation'), ('comment', 'Comment'), ('like', 'Like'), ('report', 'Report'), ('entity_create', 'Entity Create'), ('entity_delete', 'Entity Delete'), ('entity_update', 'Entity Update'), ('model_config_change', 'Model Config Change'), ('report_handle', 'Report Handle'), ('detection', 'Detection'), ('review_request', 'Review Request'), ('manual_review', 'Manual Review'), ('resource_container', 'Resource Container'), ('file_bind', 'File Bind'), ('review_text', 'Review Text'), ('material_validation', 'Material Validation'), ('create_detection_task', 'Create Detection Task'), ('create_review_request', 'Create Review Request'), ('approve_review_request', 'Approve Review Request'), ('reject_review_request', 'Reject Review Request'), ('submit_review', 'Submit Review')], db_index=True, max_length=50),
        ),
    ]
