# Generated by Django 6.0.3 on 2026-05-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_log_operation_type'),
        ('core', '0009_reviewrequest_selected_section_ids'),
    ]

    operations = [
    ]
