# Generated by Django 6.0.3 on 2026-05-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20260531_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdetectionresult',
            name='method',
            field=models.CharField(choices=[('splicing', '拼接检测'), ('blurring', '模糊检测'), ('bruteforce', '暴力篡改检测'), ('contrast', '对比度检测'), ('inpainting', '修复检测'), ('method6', 'Method-6'), ('method7', 'Method-7')], max_length=30),
        ),
    ]
